ALTER TABLE "Partnership" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Scholarship" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Achievement" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "StudentActivity" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Album" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Testimonial" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
