ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'STAF_UMUM';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DEKAN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'WADEK';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'KABAG';
