ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'DIAJUKAN';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'DISPOSISI_DEKAN';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'CEK_KETERSEDIAAN';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'PERLU_REVISI';
